name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        apt-get update && apt-get install make
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: build client debug
      run: make -C client
    - name: build client release
      run: make -C client release
    - name: build server debug
      run: make -C server
    - name: build server release
      run: make -C server release
