name: Build

on : [push]

# on:
#   push:
#     branches: [ master, dev ]
#   pull_request:
#     branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: build client
      run: make -C client
    - name: build server
      run: make -C server
